---
title: "a3_task4_cat_takata"
author: "Catherine Takata"
date: "11/5/2020"
output: html_document
---

Summary: Compare the mean size of purple urchins in CONTROL (no giant kelp removal) or ANNUAL (annual kelp removal) sections of Naples Reef in January 2010. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
```

#### Read in data set 

```{r}
urchins <- read.csv(here("data", "urchins.csv"))
```

#### Wrangle data - clean, format dates, etc - before proceeding with analysis 

```{r}
# Use clean_names() to change column names to lower snake case - will ease data analaysis and calling columns 
urchins_clean <- urchins %>% 
  clean_names()

# in a pipe sequence, change the inital date into a different format and mutate() it to add this new formatted column to the data set 
# then mutate() a new column for year, in order to easily filter data 
urchins_clean <- urchins_clean %>% 
  mutate(date_formatted = mdy(date)) %>% 
  mutate(year = year(date_formatted))

# assign the data_formatted as a "Date" class 
class(urchins_clean$date_formatted)

```

#### Begin to wrangle data, only include Naples Reef observations for purple urchins observed in January 2010 

```{r}
naples_purp <- urchins_clean %>% 
  filter(site == "NAPL",
         common_name == "Purple Urchin",
         year == 2010)
```

